name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: set up python v${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version }}

    - name: install
      run: |
        python -m pip install --upgrade pip
        make install

    - name: lint
      run: |
        make lint

    - name: test
      run: |
        make test
